language: python
python:
  - "3.6.4"
# command to run tests
services:
  - docker
before_install:
  - docker build -t aileen51669/easycrm .
script:
  - docker run -e CI=true aileen51669/easycrm nosetests -v
