language: python
python:
  - "3.6.4"
# command to run tests
services:
  - docker
before_install:
  - docker build -t aileen51669/easycrm .
script:
  - docker run -e CI=true aileen51669/easycrm nosetests -v
deploy:
  provider: elasticbeanstalk
  region: "us-east-1" ### AWS region of your choice
  app: "sample-docker-easycrm2" ### Your EB App name
  env: "Sampledockereasycrm2-env" ### Your EB App environment name
  bucket_name: "elasticbeanstalk-us-east-1-348997856332" ### S3 bucket name
  bucket_path: "EBApptest" ### S3 folder name under S3 bucket above
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
